# Generated by Django 5.2.4 on 2025-10-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_customuser_created_at_customuser_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
