# Generated by Django 5.2.4 on 2025-10-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_remove_order_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='business_user',
        ),
    ]
