# Generated by Django 5.2.4 on 2025-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0003_remove_order_business_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('business_profile_count', models.IntegerField(blank=True, null=True)),
                ('offer_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
