# Generated by Django 5.2.4 on 2025-10-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_baseinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseInfo',
        ),
    ]
