# Generated by Django 5.2.4 on 2025-10-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('coderr_app', '0005_delete_baseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_orders', to='auth_app.customuser'),
        ),
    ]
