# Generated by Django 5.2.4 on 2025-11-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('coderr_app', '0006_order_business_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('business_user', 'reviewer'), name='unique_review_per_business_user'),
        ),
    ]
